import { version } from '../package.json'
export const COLORS = 'colors' // 选填
export const DIR_PATH = 'dirPath' // 必填
export const GENERATE = 'generate' // 必填 生成地址
export const UNIT = 'unit' // 选填 单位
export const IMPORTANT = 'important' // 选填 单位
// 以下是项目配置 不从配置文件读
export const EXT_NAME = 'extNames'
export const GLOB_REG = 'globReg'

// 以下是枚举

export const JUSTIFY_CONTENT_ENMU = ['center', 'start', 'end', 'flex-start', 'flex-end', 'left', 'right', 'space-between', 'between', 'space-around', 'around', 'space-evenly', 'evenly', 'stretch', 'inherit', 'initial', 'unset', 'normal']
export const ALIGN_ITEMS_ENMU = ['baseline', 'center', 'end', 'flex-end', 'flex-start', 'inherit', 'initial', 'normal', 'self-end', 'self-start', 'start', 'stretch', 'unset']

export const CURSOR_ENMU = ['auto', 'default', 'none', 'context-menu', 'help', 'pointer', 'progress', 'wait', 'cell', 'crosshair', 'text', 'vertical-text', 'alias', 'copy', 'move', 'no-drop', 'not-allowed', 'e-resize', 'n-resize', 'ne-resize', 'nw-resize', 's-resize', 'se-resize', 'sw-resize', 'w-resize', 'ew-resize', 'ns-resize', 'nesw-resize', 'nwse-resize', 'col-resize', 'row-resize', 'all-scroll', 'zoom-in', 'zoom-out', 'grab', 'grabbing']

const UNIT_ENMU = ['cm', 'mm', 'in', 'px', 'pt', 'pc', 'em', 'ex', 'ch', 'rem', 'vw', 'vh', 'vmin', 'vmax', 'p']
export const JUSTIFY_CONTENT_ENMU_STR = JUSTIFY_CONTENT_ENMU.join('|')
export const ALIGN_ITEMS_ENMU_STR = ALIGN_ITEMS_ENMU.join('|')
export const CURSOR_ENMU_STR = CURSOR_ENMU.join('|')
export const UNIT_ENMU_STR = UNIT_ENMU.join('|')
// 文件开头
export let CSS_ANNOTATION = ''
CSS_ANNOTATION += '@charset "UTF-8";\n'
CSS_ANNOTATION += '/* https://github.com/macheteHot/css-generator-plugin/\n'
CSS_ANNOTATION += `   version: v${version}\n`
CSS_ANNOTATION += '   this file will auto generate and update\n'
CSS_ANNOTATION += '   DO NOT EDIT THIS FILE!\n'
CSS_ANNOTATION += '   DO NOT EDIT THIS FILE!\n'
CSS_ANNOTATION += '   DO NOT EDIT THIS FILE!\n'
CSS_ANNOTATION += '*/\n\n'

export const DIRECTION_MAP = new Map()
DIRECTION_MAP.set(undefined, ['']) // 全部
DIRECTION_MAP.set('x', ['left', 'right'])
DIRECTION_MAP.set('y', ['top', 'bottom'])
DIRECTION_MAP.set('t', ['top'])
DIRECTION_MAP.set('r', ['right'])
DIRECTION_MAP.set('b', ['bottom'])
DIRECTION_MAP.set('l', ['left'])
DIRECTION_MAP.set('top', ['top'])
DIRECTION_MAP.set('right', ['right'])
DIRECTION_MAP.set('bottom', ['bottom'])
DIRECTION_MAP.set('left', ['left'])
